---
- name: Ensure Jenkins GPG key is added
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "644"
- name: Ensure Jenkins repo is added
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    filename: jenkins
    state: present
- name: Ensure Java and Jenkins are installed
  ansible.builtin.apt: 
    name: 
      - openjdk-17-jdk
      - jenkins
    update_cache: true
    state: present
