---
  - name: Ensure service config folder exists
    ansible.builtin.file: 
      path: /etc/systemd/system/jenkins.service.d
      state: directory
      mode: "644"
  - name: Ensure Jenkins home exists
    ansible.builtin.file: 
      path: "{{ jenkins_home }}"
      state: directory
      group: jenkins
      owner: jenkins
      mode: "775"
  - name: Check if initial setup file exists
    ansible.builtin.stat: 
      path: "{{ jenkins_home }}/init-setup-flag-file"
    register: init_setup_flag_file
  - name: Ensure config file for service exists
    ansible.builtin.template: 
      src: systemd.conf.j2
      dest: /etc/systemd/system/jenkins.service.d/override.conf
      mode: "644"
    register: jenkins_service_config
  - name: Ensure Jenkins restart on config change
    ansible.builtin.systemd_service: 
      name: jenkins
      state: restarted
      daemon_reload: true
    when: jenkins_service_config.changed and init_setup_flag_file.stat.exists
  - name: Ensure groovy scripts directory exists
    ansible.builtin.file: 
      path: "{{ jenkins_home }}/init.groovy.d"
      state: directory
      owner: jenkins
      group: jenkins
      mode: "775"
  - name: Ensure initial admin is created
    ansible.builtin.template:
      src: security.groovy.j2
      dest: "{{ jenkins_home }}/init.groovy.d/security.groovy"
      mode: "744"
      group: jenkins
      owner: jenkins
    when: not init_setup_flag_file.stat.exists
  - name: Ensure initial setup flag file exists
    ansible.builtin.file: 
      path: "{{ jenkins_home }}/init-setup-flag-file"
      owner: jenkins
      group: jenkins
      mode: "644"
      state: touch
    changed_when: false
